hackathon_platform/apps/issues/urls.py
from django.conf.urls import url

from .views import IssueListView, IssueDetailView, IssueCreateView
from hackathons.views import HackathonCreateView


urlpatterns = [
	url(r'^$', IssueListView.as_view(), name='list'),
	url(r'^(?P<pk>\d+)/$', IssueDetailView.as_view(), name='detail'),
	url(r'^create/$', IssueCreateView.as_view(), name='create'),
	url(r'^(?P<pk>\d+)/hackathons/$', HackathonCreateView.as_view(), name='create_hackathon'),

]

hackathon_platform/apps/profiles/urls.py
__author__ = 'ssureymoon'
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^login/$', views.UserAuthView.as_view(), name='login'),
	url(r'^signup/$', views.UserCreateView.as_view(), name='signup'),
]

hackathon_platform/apps/projects/urls.py
__author__ = 'ssureymoon'
from django.conf.urls import url

from .views import ProjectListView


urlpatterns = [
	url(r'^$', ProjectListView.as_view(), name='list'),
]

hackathon_platform/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'core.views.home', name='home'),
    url(r'^how-it-works/$', 'core.views.how_it_works', name='how_it_works'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/', include('profiles.urls', namespace='profiles')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^issues/', include('issues.urls', namespace='issues')),
    url(r'^hackathons/', include('hackathons.urls', namespace='hackathons')),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hackathon_platform/apps/core/models.py
from django.db import models

# Create your models here.
class TimeStampedModel(models.Model):
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		abstract = True

hackathon_platform/apps/hackathons/models.py
from django.db import models
from django.conf import settings

from core.models import TimeStampedModel
from core.utils import GenerateRandomFilename
from issues.models import Issue

generate_random_filename = GenerateRandomFilename('hackathons')


class Hackathon(TimeStampedModel):

	title = models.CharField(max_length=200)
	snippet = models.CharField(max_length=100)
	picture = models.ImageField(upload_to=generate_random_filename, blank=True, null=True)
	description = models.TextField()
	due_date_time = models.DateTimeField()
	contribute_to = models.ForeignKey(Issue)
	host = models.ForeignKey(settings.AUTH_USER_MODEL)

hackathon_platform/apps/issues/models.py
from django.db import models
from django.conf import settings

from core.models import TimeStampedModel
from core.utils import GenerateRandomFilename

generate_random_filename = GenerateRandomFilename('issues')

COUNTRY_CHOICES = (
	('US', 'United States'),
	('KR', 'KOREA, REPUBLIC OF'),
	('KH', 'Cambodia'),
	('VN', 'Viet Nam'),
	('ID', 'Indonesia'),
	('KE', 'KENYA'),
	('MY', 'Malaysia'),
	('TZ', 'TANZANIA'),
	('GG', 'Global'),
)

# Create your models here.
class Issue(TimeStampedModel):

	title = models.CharField(max_length=200)
	snippet = models.CharField(max_length=100)
	picture = models.ImageField(upload_to=generate_random_filename, blank=True, null=True)
	description = models.TextField()
	country = models.CharField(max_length=2, choices=COUNTRY_CHOICES, default='GG')
	raiser = models.ForeignKey(settings.AUTH_USER_MODEL)

hackathon_platform/apps/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):

	def __unicode__(self):
		return self.username

hackathon_platform/apps/projects/models.py
from django.db import models

# Create your models here.

hackathon_platform/apps/hackathons/forms.py
from django import forms
from .models import Hackathon


class HackathonCreateForm(forms.ModelForm):
    picture = forms.ImageField()
    due_date = forms.DateField()
    due_time = forms.TimeField()

    class Meta:
        model = Hackathon
        fields = ['title', 'snippet', 'due_date', 'description', 'picture', 'due_time']

    def clean(self):
        print self.cleaned_data

hackathon_platform/apps/issues/forms.py
from django import forms

from .models import COUNTRY_CHOICES, Issue


class IssueCreateForm(forms.ModelForm):
    country = forms.ChoiceField(choices=COUNTRY_CHOICES)
    picture = forms.ImageField()

    class Meta:
        model = Issue
        fields = ['title', 'snippet', 'country', 'description', 'picture']

hackathon_platform/apps/profiles/forms.py
from django.contrib.auth.forms import UserCreationForm

__author__ = 'ssureymoon'
from django import forms
from profiles.models import User


class LoginForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username', 'password']


class RegistrationForm(UserCreationForm):

	# confirm = forms.CharField(max_length=100)

	class Meta:
		model = User
		fields = ["email", 'username',]

	# def clean_confirm(self):
	# 	if not self.cleaned_data['confirm']:
	# 		raise forms.ValidationError("Enter a confirm password.")
	# 	return self.cleaned_data['confirm']

hackathon_platform/apps/core/views.py
from django.shortcuts import render

# Create your views here.
from hackathons.models import Hackathon
from issues.models import Issue


def home(request):
	issues = Issue.objects.all()[:4]
	hackathons = Hackathon.objects.all()[:4]
	return render(request, 'home.html', { 'issues': issues, 'hackathons': hackathons })

def how_it_works(request):
	return render(request, 'howitworks.html')

hackathon_platform/apps/hackathons/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.datetime_safe import datetime
from django.views.generic import ListView, View
from braces.views import LoginRequiredMixin

from .models import Hackathon
from .forms import HackathonCreateForm
from issues.models import Issue


class HackathonListView(ListView):
	model = Hackathon
	template_name = "hackathons/list.html"


class HackathonDetailView(View):

	def get(self, request, *args, **kwargs):
		hackathon = get_object_or_404(Hackathon, pk=kwargs['pk'])
		issue = hackathon.contribute_to
		return render(request, "hackathons/detail.html", {'hackathon': hackathon, 'issue': issue})


class HackathonCreateView(LoginRequiredMixin, View):

	def get(self, request, *args, **kwargs):
		issue = get_object_or_404(Issue, pk=kwargs['pk'])
		form = HackathonCreateForm()
		return render(request, "hackathons/create.html", {'form': form, "issue": issue})

	def post(self, request, *args, **kwargs):
		issue = get_object_or_404(Issue, pk=kwargs['pk'])
		form = HackathonCreateForm(request.POST, request.FILES)
		
		is_vaild = form.is_valid()

		if is_vaild:

			due_date = form.cleaned_data['due_date']
			due_time = form.cleaned_data['due_time']

			hackathon = form.save(commit=False)
			hackathon.due_date_time = datetime.combine(due_date, due_time)
			hackathon.host = request.user
			hackathon.contribute_to = issue
			hackathon.save()
			return redirect("hackathons:detail", hackathon.pk)
		return redirect("hackathons:create")

hackathon_platform/apps/issues/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DetailView, View

from braces.views import LoginRequiredMixin

from .models import Issue, COUNTRY_CHOICES
from .forms import IssueCreateForm


class IssueActionMixin(object):

	@property
	def success_msg(self):
		return NotImplemented

	def form_valid(self, form):
		messages.info(self.request, self.success_msg)
		return super(IssueActionMixin, self).form_valid(form)


class IssueCreateView(LoginRequiredMixin, IssueActionMixin, View):
	success_msg = "Created"

	def get(self, request):
		form = IssueCreateForm()
		return render(request, "issues/create.html", {'form': form})

	def post(self, request):
		form = IssueCreateForm(request.POST, request.FILES)

		if form.is_valid():
			issue = form.save(commit=False)
			issue.raiser = request.user
			issue.save()
			return redirect("issues:detail", issue.pk)
		return redirect("issues:create")



class IssueListView(ListView):
	model = Issue
	template_name = "issues/list.html"

	def get_queryset(self):
		queryset = super(IssueListView, self).get_queryset()

		q = self.request.GET.get('q')
		if q:
			return queryset.filter(title__icontains=q)
		return queryset

class IssueDetailView(IssueActionMixin, View):
	success_msg = "Updated"

	def get(self, request, *args, **kwargs):
		issue = get_object_or_404(Issue, pk=kwargs['pk'])
		return render(request, "issues/detail.html", {'issue': issue})

hackathon_platform/apps/profiles/views.py
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, View
from django.contrib.auth import authenticate, login, logout

from profiles.models import User
from . import forms


# Create your views here.
class UserAuthView(View):

	def get(self, request):
		return render(request, "profiles/login.html", {'action':'login'})

	def post(self, request):

		form = AuthenticationForm(data=request.POST)

		if form.is_valid():
			print "hi"
			user = authenticate(
				username=form.cleaned_data['username'],
				password=form.cleaned_data['password']
			)

			if user is not None:
				login(request, user)
				return redirect('home')
		messages.error(request, "login failed")
		return render(request, "profiles/login.html", {'action':'login'})


class UserCreateView(View):

	def get(self, request):
		return render(request, "profiles/login.html", {'action':'signup'})

	def post(self, request):
		form = forms.RegistrationForm(request.POST)

		if form.is_valid():
			user = form.save()
			if user:
				user.backend = 'django.contrib.auth.backends.ModelBackend'
				login(request, user)
				messages.info(request, "signup success")
				return redirect("home")
		messages.error(request, "signup failed")
		return render(request, "profiles/login.html", {"action":"signup"})

hackathon_platform/apps/projects/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import View


class ProjectListView(View):

	def get(self, request, *args, **kwargs):
		return render(request, "projects/list.html")

hackathon_platform/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="{% block description %}{% endblock %}" />
    <meta name="keywords" content="{% block keywords %}{% endblock %}" />
    <meta name="viewport" content="{% block viewport %}width=device-width"{% endblock %}>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}Hack Linker{% endblock title %}</title>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="icon" type="image/gif" href="{% static 'img/favicon.gif' %}">

    {% block css %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
        <!-- font Awesome CSS -->
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="//oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="//oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>
      {% block navbar %}
          <div class="nav-wrapper">
              <div class="">

                  <nav class="navbar navbar-default navbar-inverse" role="navigation">
                    <div class="container-fluid">
                      <!-- Brand and toggle get grouped for better mobile display -->
                      <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'home' %}">Hack Linker</a>
                      </div>

                      <!-- Collect the nav links, forms, and other content for toggling -->
                      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                          <li><a href="{% url 'hackathons:list' %}">Hackathons</a></li>
                          <li><a href="{% url 'projects:list' %}">Projects</a></li>
                          <li><a href="{% url 'issues:list' %}">Issues</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                          <li><a href="{% url 'how_it_works' %}">How it works</a></li>
                          <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Accounts <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">


                            {% if user.is_authenticated %}
                              <li><a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a></li>
                            {% else %}
                              <li><a href="{% url 'profiles:signup' %}">Login</a></li>
                            {% endif %}
                            </ul>
                          </li>
                        </ul>
                      </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                  </nav>

              </div>
              <!-- /.container -->
          </div>
    {% endblock %}

    {% block content %}
        <div class="container">


            <p>Use this document as a way to quick start any new project.</p>


        </div> <!-- /container -->
    {% endblock content %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <!-- Bootstrap JavaScript -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

        <!-- Custom JavaScript -->
        <script src="{% static 'js/custom.js' %}"></script>
        <script src="{% static 'js/scripts.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>

hackathon_platform/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="full-size" id="wrapper">

        <div id="mainCarousel" class="carousel slide" data-ride="carousel">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                <li data-target="#mainCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#mainCarousel" data-slide-to="1"></li>
                <li data-target="#mainCarousel" data-slide-to="2"></li>
              </ol>

              <!-- Wrapper for slides -->
              <div class="carousel-inner" role="listbox">
                <div class="item slide active">
                  <img src="{% static 'img/slide1.jpg' %}" alt="silde1">
                  <div class="carousel-caption">
                    <h1>World has lots of issues, needs help.</h1>
                  </div>
                </div>

                <div class="item slide">
                  <img src="{% static 'img/slide2.jpg' %}" alt="silde2">
                  <div class="carousel-caption">
                    <h1>Software and Hardware can solve any problems.</h1>
                  </div>
                </div>

                <div class="item slide">
                  <img src="{% static 'img/slide3.jpg' %}" alt="slide3">
                  <div class="carousel-caption">
                    <h1>Hack the world. Be borderless.</h1>
                  </div>
                </div>
              </div>

              <!-- Controls -->
              <a class="left carousel-control" href="#mainCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#mainCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
              </a>
        </div>


        <div class="container">

            <div class="section">
                <div class="row">
                    <h2>Featured Issues</h2>
                    {% if issues %}
                        {% for issue in issues %}
                            <div class="col-md-3">
                                <a href="{% url 'issues:detail' issue.pk %}" class="thumbnail">
                                    <img src="{% static 'img/slide3.jpg' %}" alt="">
                                </a>
                                <h3>{{ issue.title }}</h3>
                                <p>{{ issue.snippet }}</p>
                                <p>{{ issue.country }}</p>
                                <a href="{% url 'issues:detail' issue.pk %}" class="btn btn-primary btn-sm">Read More</a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Issue One</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Issue Two</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Issue Three</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Issue Four</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                    {% endif %}
                </div>

                <hr>

                <div class="row">
                    <h2>Featured Hackathons</h2>
                    {% if hackathons %}
                        {% for hackathon in hackathons %}
                            <div class="col-md-3">
                                <a href="{% url 'hackathons:detail' hackathon.pk %}" class="thumbnail">
                                    <img src="{% static 'img/slide3.jpg' %}" alt="">
                                </a>
                                <h3>{{ hackathon.title }}</h3>
                                <p>{{ hackathon.snippet }}</p>
                                <a href="{% url 'hackathons:detail' hackathon.pk %}" class="btn btn-primary btn-sm">Read More</a>
                            </div>
                        {% endfor %}
                    {% else %}

                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Hackathon One</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Hackathon Two</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Hackathon Three</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Hackathon Four</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                    {% endif %}
                </div>

                <hr>

                <div class="row">
                    <h2>Featured Projects</h2>
                    {% if projects %}
                        {% for project in projects %}
                            <div class="col-md-3">
                                <a href="{% url 'projects:detail' project.pk %}" class="thumbnail">
                                    <img src="{{ project.picture.url }}" alt="">
                                </a>
                                <h3>{{ hackathon.title }}</h3>
                                <p>{{ hackathon.snippet }}</p>
                                <a href="{% url 'projects:detail' project.pk %}" class="btn btn-primary btn-sm">Read More</a>
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Project One</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Project Two</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Project Three</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                        <div class="col-md-3">
                            <a href="#" class="thumbnail">
                                <img src="http://placehold.it/300x200" alt="">
                            </a>
                            <h3>Project Four</h3>
                            <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                            <a href="#" class="btn btn-primary btn-sm">Read More</a>
                        </div>
                    {% endif %}
                </div>
            </div>
            <!-- /.section -->

            <hr>

            <div class="section">
                <div class="row">
                    <div class="col-md-7">
                        <h1>Font Awesome Is There</h1>
                        <p>Font Awesome is included and from MaxCDN <span class="fa fa-heart"></span></p>
                    </div>
                    <div class="col-md-5">
                        <img src="http://placehold.it/450x200" class="img-responsive" alt="">
                    </div>
                </div>
            </div>
            <!-- /.section -->

            <hr>

            <footer>
                <div class="copy-rights clearfix">
                    <div class="pull-left">
                        All Copy Rights Reserved For YourCompany 201*
                    </div>
                    <div class="pull-right">
                        by <a href="http://scoopthemes.com">Scoop Themes</a>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.container -->


    </div>
{% endblock content %}

hackathon_platform/templates/howitworks.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="full-size" id="wrapper">
        <div class="container">
            <div class="main-content">
                <h1>Hack the world. Be borderless.</h1>
                <div>
                    <img src="{% static 'img/how_it_work.png' %}" alt='how it works'/>
                </div>
                <table class='table' style="margin-top:15px;">
                    <tbody>
                        <tr>
                            <td><div class="number-circle">1</div></td>
                            <td>Local entrepreneurs or engineers upload some issues they have confronted while operating business.</td>
                        </tr>
                        <tr>
                            <td><div class="number-circle">2</div></td>
                            <td>After checking the issues, we contact some sponsor, and throw a hackathon to solve the issues. </td>
                        </tr>
                        <tr>
                            <td><div class="number-circle">3</div></td>
                            <td>Hackers join the hackathon and submit projects with technical skills or creative ideas.</td>
                        </tr>
                        <tr>
                            <td><div class="number-circle">4</div></td>
                            <td>During the hackathon, hackers can communicates with the issue raisers (local entrepreneurs or engineers) to get a better understanding, and to find more practical solution.</td>
                        </tr>
                        <tr>
                            <td><div class="number-circle">5</div></td>
                            <td>The issue raisers vote on the project which fits to their situations.</td>
                        </tr>
                        <tr>
                            <td><div class="number-circle">6</div></td>
                            <td>Anyone may vote on projects which they like, and share them thorough SNS.
This action gathers much attention from the public.<br>
People can also invest some money to the issue. The money invested will be used to provide airline tickets to winners.</td>
                        </tr>
                        <tr>
                            <td><div class="number-circle">7</div></td>
                            <td>The winners get prizes, they will get a chance to work with the local entrepreneurs for a couple of months by flying to the countries.</td>
                        </tr>
                        <tr>
                            <td><div class="number-circle">8</div></td>
                            <td>People who invest money get periodic reports, and even small benefit.</td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- /.section -->

            <footer>
                <div class="copy-rights clearfix">
                    <div class="pull-left">
                        All Copy Rights Reserved For YourCompany 201*
                    </div>
                    <div class="pull-right">
                        by <a href="http://scoopthemes.com">Scoop Themes</a>
                    </div>
                </div>
            </footer>

        </div>
        <!-- /.container -->
    </div>
{% endblock content %}