hackathon_platform/apps/issues/urls.py
from django.conf.urls import url

from .views import IssueListView, IssueDetailView, IssueCreateView
from hackathons.views import HackathonCreateView


urlpatterns = [
	url(r'^$', IssueListView.as_view(), name='list'),
	url(r'^(?P<pk>\d+)/$', IssueDetailView.as_view(), name='detail'),
	url(r'^create/$', IssueCreateView.as_view(), name='create'),
	url(r'^(?P<pk>\d+)/hackathons/$', HackathonCreateView.as_view(), name='create_hackathon'),

]

hackathon_platform/apps/profiles/urls.py
__author__ = 'ssureymoon'
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^login/$', views.UserAuthView.as_view(), name='login'),
	url(r'^signup/$', views.UserCreateView.as_view(), name='signup'),
]

hackathon_platform/apps/projects/urls.py
__author__ = 'ssureymoon'
from django.conf.urls import url

from .views import ProjectListView


urlpatterns = [
	url(r'^$', ProjectListView.as_view(), name='list'),
]

hackathon_platform/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'core.views.home', name='home'),
    url(r'^how-it-works/$', 'core.views.how_it_works', name='how_it_works'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/', include('profiles.urls', namespace='profiles')),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^issues/', include('issues.urls', namespace='issues')),
    url(r'^hackathons/', include('hackathons.urls', namespace='hackathons')),
    url(r'^admin/', include(admin.site.urls)),
    url('^', include('django.contrib.auth.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hackathon_platform/apps/core/models.py
from django.db import models

# Create your models here.
class TimeStampedModel(models.Model):
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		abstract = True

hackathon_platform/apps/hackathons/models.py
from django.db import models
from django.conf import settings

from core.models import TimeStampedModel
from core.utils import GenerateRandomFilename
from issues.models import Issue

generate_random_filename = GenerateRandomFilename('hackathons')


class Hackathon(TimeStampedModel):

	title = models.CharField(max_length=200)
	snippet = models.CharField(max_length=100)
	picture = models.ImageField(upload_to=generate_random_filename, blank=True, null=True)
	description = models.TextField()
	due_date_time = models.DateTimeField()
	contribute_to = models.ForeignKey(Issue)
	host = models.ForeignKey(settings.AUTH_USER_MODEL)

hackathon_platform/apps/issues/models.py
from django.db import models
from django.conf import settings

from core.models import TimeStampedModel
from core.utils import GenerateRandomFilename

generate_random_filename = GenerateRandomFilename('issues')

COUNTRY_CHOICES = (
	('US', 'United States'),
	('KR', 'KOREA, REPUBLIC OF'),
	('KH', 'Cambodia'),
	('VN', 'Viet Nam'),
	('ID', 'Indonesia'),
	('KE', 'KENYA'),
	('MY', 'Malaysia'),
	('TZ', 'TANZANIA'),
	('GG', 'Global'),
)

# Create your models here.
class Issue(TimeStampedModel):

	title = models.CharField(max_length=200)
	snippet = models.CharField(max_length=100)
	picture = models.ImageField(upload_to=generate_random_filename, blank=True, null=True)
	description = models.TextField()
	country = models.CharField(max_length=2, choices=COUNTRY_CHOICES, default='GG')
	raiser = models.ForeignKey(settings.AUTH_USER_MODEL)

hackathon_platform/apps/profiles/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class User(AbstractUser):

	def __unicode__(self):
		return self.username

hackathon_platform/apps/projects/models.py
from django.db import models

# Create your models here.

hackathon_platform/apps/hackathons/forms.py
from django import forms
from .models import Hackathon


class HackathonCreateForm(forms.ModelForm):
    picture = forms.ImageField()
    due_date = forms.DateField()
    due_time = forms.TimeField()

    class Meta:
        model = Hackathon
        fields = ['title', 'snippet', 'due_date', 'description', 'picture', 'due_time']

    def clean(self):
        print self.cleaned_data

hackathon_platform/apps/issues/forms.py
from django import forms

from .models import COUNTRY_CHOICES, Issue


class IssueCreateForm(forms.ModelForm):
    country = forms.ChoiceField(choices=COUNTRY_CHOICES)
    picture = forms.ImageField()

    class Meta:
        model = Issue
        fields = ['title', 'snippet', 'country', 'description', 'picture']

hackathon_platform/apps/profiles/forms.py
from django.contrib.auth.forms import UserCreationForm

__author__ = 'ssureymoon'
from django import forms
from profiles.models import User


class LoginForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username', 'password']


class RegistrationForm(UserCreationForm):

	# confirm = forms.CharField(max_length=100)

	class Meta:
		model = User
		fields = ["email", 'username',]

	# def clean_confirm(self):
	# 	if not self.cleaned_data['confirm']:
	# 		raise forms.ValidationError("Enter a confirm password.")
	# 	return self.cleaned_data['confirm']

hackathon_platform/apps/core/views.py
from django.shortcuts import render

# Create your views here.
from hackathons.models import Hackathon
from issues.models import Issue


def home(request):
	issues = Issue.objects.all()[:4]
	hackathons = Hackathon.objects.all()[:4]
	return render(request, 'home.html', { 'issues': issues, 'hackathons': hackathons })

def how_it_works(request):
	return render(request, 'howitworks.html')

hackathon_platform/apps/hackathons/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.datetime_safe import datetime
from django.views.generic import ListView, View
from braces.views import LoginRequiredMixin

from .models import Hackathon
from .forms import HackathonCreateForm
from issues.models import Issue


class HackathonListView(ListView):
	model = Hackathon
	template_name = "hackathons/list.html"


class HackathonDetailView(View):

	def get(self, request, *args, **kwargs):
		hackathon = get_object_or_404(Hackathon, pk=kwargs['pk'])
		issue = hackathon.contribute_to
		return render(request, "hackathons/detail.html", {'hackathon': hackathon, 'issue': issue})


class HackathonCreateView(LoginRequiredMixin, View):

	def get(self, request, *args, **kwargs):
		issue = get_object_or_404(Issue, pk=kwargs['pk'])
		form = HackathonCreateForm()
		return render(request, "hackathons/create.html", {'form': form, "issue": issue})

	def post(self, request, *args, **kwargs):
		issue = get_object_or_404(Issue, pk=kwargs['pk'])
		form = HackathonCreateForm(request.POST, request.FILES)
		
		is_vaild = form.is_valid()

		if is_vaild:

			due_date = form.cleaned_data['due_date']
			due_time = form.cleaned_data['due_time']

			hackathon = form.save(commit=False)
			hackathon.due_date_time = datetime.combine(due_date, due_time)
			hackathon.host = request.user
			hackathon.contribute_to = issue
			hackathon.save()
			return redirect("hackathons:detail", hackathon.pk)
		return redirect("hackathons:create")

hackathon_platform/apps/issues/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DetailView, View

from braces.views import LoginRequiredMixin

from .models import Issue, COUNTRY_CHOICES
from .forms import IssueCreateForm


class IssueActionMixin(object):

	@property
	def success_msg(self):
		return NotImplemented

	def form_valid(self, form):
		messages.info(self.request, self.success_msg)
		return super(IssueActionMixin, self).form_valid(form)


class IssueCreateView(LoginRequiredMixin, IssueActionMixin, View):
	success_msg = "Created"

	def get(self, request):
		form = IssueCreateForm()
		return render(request, "issues/create.html", {'form': form})

	def post(self, request):
		form = IssueCreateForm(request.POST, request.FILES)

		if form.is_valid():
			issue = form.save(commit=False)
			issue.raiser = request.user
			issue.save()
			return redirect("issues:detail", issue.pk)
		return redirect("issues:create")



class IssueListView(ListView):
	model = Issue
	template_name = "issues/list.html"

	def get_queryset(self):
		queryset = super(IssueListView, self).get_queryset()

		q = self.request.GET.get('q')
		if q:
			return queryset.filter(title__icontains=q)
		return queryset

class IssueDetailView(IssueActionMixin, View):
	success_msg = "Updated"

	def get(self, request, *args, **kwargs):
		issue = get_object_or_404(Issue, pk=kwargs['pk'])
		return render(request, "issues/detail.html", {'issue': issue})

hackathon_platform/apps/profiles/views.py
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, View
from django.contrib.auth import authenticate, login, logout

from profiles.models import User
from . import forms


# Create your views here.
class UserAuthView(View):

	def get(self, request):
		return render(request, "profiles/login.html", {'action':'login'})

	def post(self, request):

		form = AuthenticationForm(data=request.POST)

		if form.is_valid():
			print "hi"
			user = authenticate(
				username=form.cleaned_data['username'],
				password=form.cleaned_data['password']
			)

			if user is not None:
				login(request, user)
				return redirect('home')
		messages.error(request, "login failed")
		return render(request, "profiles/login.html", {'action':'login'})


class UserCreateView(View):

	def get(self, request):
		return render(request, "profiles/login.html", {'action':'signup'})

	def post(self, request):
		form = forms.RegistrationForm(request.POST)

		if form.is_valid():
			user = form.save()
			if user:
				user.backend = 'django.contrib.auth.backends.ModelBackend'
				login(request, user)
				messages.info(request, "signup success")
				return redirect("home")
		messages.error(request, "signup failed")
		return render(request, "profiles/login.html", {"action":"signup"})

hackathon_platform/apps/projects/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import View


class ProjectListView(View):

	def get(self, request, *args, **kwargs):
		return render(request, "projects/list.html")

hackathon_platform/templates/issues/create.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- /.nav-wrapper -->

    <div class="container">
        <div class='main-content'>
            <h2>Elect an issue!</h2>
            <form name="form" id="matter-form" action="{% url 'issues:create' %}" method="POST" enctype="multipart/form-data" role="form">
                {% csrf_token %}
                <fieldset class="form-group">
                    <label for="title">Title</label>
                    <input type="text" name="title" id="title" class="form-control" required />
                </fieldset>
                <fieldset class="form-group">
                    <label for="snippet">Summary(100 characters)</label>
                    <input type="text" name="snippet" id="snippet" class="form-control" required />
                </fieldset>
                <fieldset class="form-group">
                    <label for="picture">Picture</label>
                    <input type="file" name="picture" id="picture" class="form-control" />
                </fieldset>

                <fieldset class="form-group">
                    <label for="description">Description</label>
                    <textarea rows="10" name="description" form="matter-form" id="description" class="form-control" required></textarea>
                </fieldset>

                <fieldset class="form-group">
                    <label for="country">Country</label>
                    <select type="textarea" name="country" id="country" class="form-control" required>
                        {% for choice in form.country.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    </select>
                </fieldset>

                <button type="submit" class="btn btn-primary">Create</button>

            </form>
        </div>
    </div>
{% endblock %}

hackathon_platform/templates/issues/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- /.nav-wrapper -->

    <div class="container">
        <div class='main-content'>
            <h2>{{ issue.title }}</h2>
            <h4>Summary:</h4><p>{{ issue.snippet }}</p>

            <img class="picture" src="{% static 'img/slide3.jpg' %}" />

            <h4>Description:</h4><p class="text-box">{{ issue.description }}</p>
            <h4>Location:</h4><p>{{ issue.country }}</p>
        </div>
        <a href="{% url 'issues:create_hackathon' issue.pk %}">
            <button type="button" class="btn btn-primary btn-lg">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Throw a hackathon
            </button>
        </a>
    </div>

{% endblock %}

hackathon_platform/templates/issues/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block css %}
    {{ block.super }}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- /.nav-wrapper -->

    <div class="container">
        <div class='main-content'>
            <h2>Issues</h2>
            <div class="row">
                <div class="col-md-6">

                    <form action="{% url 'issues:list' %}" method="GET">
                        <div class="input-group">
                            <input class="form-control" type="text" name="q" placeholder="search for a title of an issue"/>
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                </button>
                            </span>
                        </div>
                    </form>

                </div>
                <div class="col-md-1" style="margin-top:10px;">
                    <p>OR</p>
                </div>
                <div class="col-md-5">
                    <a href="{% url 'issues:create' %}">
                        <button type="button" class="btn btn-info">
                          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Elect an issue
                        </button>
                    </a>
                </div>
            </div>



            <div class="section">
                <div class="row">
                    {% for issue in object_list %}
                        <div class="col-md-3 content-box">
                            <a href="{% url 'issues:detail' issue.pk %}" class="thumbnail">
                                <img src="{% static 'img/slide3.jpg' %}" alt="">
                            </a>
                            <h3>{{ issue.title }}</h3>
                            <p>{{ issue.snippet }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
       </div>
    </div>
{% endblock %}